language: scala
sudo: required
jdk: openjdk8
scala:
  - 2.11.11
before_install:
  - mkdir -p /opt
  - wget -q -O /opt/spark.tgz https://archive.apache.org/dist/spark/spark-2.2.0/spark-2.2.0-bin-hadoop2.7.tgz
  - tar xzf /opt/spark.tgz -C /opt/
  - rm /opt/spark.tgz
  - export SPARK_HOME=/opt/spark-2.2.0-bin-hadoop2.7
  - export PATH=$PATH:/opt/spark-2.2.0-bin-hadoop2.7/bin
branches:
  only:
    - main
    - /^release-.*$/
before_deploy:
  - sbt ++$TRAVIS_SCALA_VERSION assembly
deploy:
  provider: releases
  api_key:
    secure: "Kl+mg4OuDAuxDC7qqKqw2nDRUNNSdF0kHJO5vqFpmDT48c3mNYaivHKrTOo2EXpiSPKhLvXzVH7dI5QIuA0iBpguE9aReKO7ZSLP4hoF90Y2UnYvIaS26whSq5Lu9IjAlK8lHMUtHayUgiAyKwdXlDfogsjpz6JIyrMCqoLrwbKXo47HvDaZSxQq8PFAmw7W/SL0eu2zA3P4EMZSpqiYo6vKcGkQ6PuDF+HNMEhHazo4HelmKOioduXwLuKJk6kWSb9tFeU1Jx5707lHzi0Ti8He/C3VrZxBbQvoPfj5Ca8YPkPe+hpoIfC6SmHlfGlZEWxbKDW+geZ0FTIR3bM3y8KL8GwvUFx8VbxPQM1vm6oALXOTYFShRCf0G5YrEEFhx9hS9sc1shH7sSfyox7K8ZN4NjPn2Qq3C9/6yY/w7OyPHQbc01qrKQbzSKM/QPaSQIl910gaqfbpJx+rXmxP8gsr8jCu8HUxwSuUS7zLTA9/nwBJ87HnrzeIZEa6/0p1j23VESgTFAZIO+1hBSDz2RxrqZTFlwVr4R9ihGudJxPL62BnkghuiwxzNQTvVZ5Die4GeFKVDrvBw/aXP5J7yarT36hE/eWVoaxZ9kr54rZglKZOHmY0lyQekTsxnLjj4HA2zmmtZyEInCw/7eWyxV2/B72Z0JHYzo3yklxd2uc="
  file_glob: true
  file: target/scala-2.11/**/*.jar
  skip_cleanup: true
  on:
    tags: true
