language: scala
sudo: required
jdk: openjdk8
scala:
  - 2.11.11
before_install:
  - mkdir -p /opt
  - wget -q -O /opt/spark.tgz https://archive.apache.org/dist/spark/spark-2.2.0/spark-2.2.0-bin-hadoop2.7.tgz
  - tar xzf /opt/spark.tgz -C /opt/
  - rm /opt/spark.tgz
  - export SPARK_HOME=/opt/spark-2.2.0-bin-hadoop2.7
  - export PATH=$PATH:/opt/spark-2.2.0-bin-hadoop2.7/bin
branches:
  only:
    - main
